server:
  port: 8010
spring:
  application:
    name: ms-consumer-movie
#将微服务注册到Eureka服务器上
eureka: 
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance: 
      prefer-ip-address: true
ms-provider-user:  #服务名字
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置Ribbon的规则为随机，这样的配置比用java config要简单