server:
  port: 8000
spring:
  application:
    name: ms-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

#info: 
#   app:
#     name: ms-provider-user
#     encoding: UTF-8
#     java:
#      source: 1.8.0_121
#      target: 1.8.0_121

#将微服务注册到Eureka服务器上
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance: 
      prefer-ip-address: true

